name: documenso-development

# NOTE: Uncomment commented out custom network for local development with BK's docker container

services:
  documensodb:
    image: postgres:15
    container_name: documensodb
    environment:
      - POSTGRES_USER=documenso
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=documenso
    ports:
      - 54320:5432
    # networks:
    #   - my-custom-created-network

  inbucket:
    image: inbucket/inbucket
    container_name: mailserver
    ports:
      - 9000:9000
      - 2500:2500
      - 1100:1100
    # networks:
    #   - my-custom-created-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - 9002:9002
      - 9001:9001
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: documenso
      MINIO_ROOT_PASSWORD: password
    entrypoint: sh
    command: -c 'mkdir -p /data/documenso && minio server /data --console-address ":9001" --address ":9002"'
    # networks:
    #   - my-custom-created-network

volumes:
  minio:
# networks:
#   my-custom-created-network:
#     external: true
